version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    reviewers: castastrophe
    open-pull-requests-limit: 10
    commit-message:
      include: scope
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "23:00"
      timezone: "America/New_York"
